### ISSUE TITLE
Try using T5 relative positioning instead of RoPE

### ISSUE THREAD

**Issue by mxkrn** [lucidrains/soundstorm-pytorch#15]
[This paper](https://arxiv.org/abs/2305.19466) shows that RoPE consistently underperforms T5 rel pos in various language-based logic problems. It might be interesting to explore a version of SoundStorm that uses T5 rel. pos. instead? Although these tasks are not exactly comparable, it does look like RoPE consistently underperforms other approaches

**Comment by lucidrains** [comment]
yup sure, can add this, but it would turn off flash attention, just fyi (it isn't compatible with learned biases)

**Comment by lucidrains** [comment]
@mxkrn ok, should work now if [this keyword argument](https://github.com/lucidrains/soundstorm-pytorch/commit/7ef65a9744e626fe9d88e973dc5a959cbfe9d391#diff-94b3b0edafb12945437f40c2b5de1901b03e10a569737cac5a2795a458a00e31R403) is set to `True`
