### ISSUE TITLE
README.md sample code error

### ISSUE THREAD

**Issue by dmtrung14** [lucidrains/soundstorm-pytorch#24]
I found a diminutive error in the README.md file, where `num_quantizers` in SoundStorm does not agree with that of the conformer. 

In particular, the second code snippet should have been : 

```python
conformer = ConformerWrapper(
    codebook_size = 1024,
    num_quantizers = 12,
    conformer = dict(
        dim = 512,
        depth = 2
    ),
)

soundstream = SoundStream(
    codebook_size = 1024,
    rq_num_quantizers = 12,
    attn_window_size = 128,
    attn_depth = 2
)
```

I reckon `12` could have been anything, but they need to be the same. Otherwise, we will bump in to some assertion errors.

**Comment by lucidrains** [comment]
@dmtrung14 oops yea... thanks!
