### ISSUE TITLE
Simple mini train and test example?

### ISSUE THREAD

**Issue by pchankh** [lucidrains/soundstorm-pytorch#3]
As always, great appreciation for your prompt and illustrative implementation. Thank you very much.
Is it possible to implement some simple mini examples to train and test with current framework implementation repo alongside your repo. That will immensely speed up community understanding of closed source results and perhaps accelerate the test of their claimed results.
Cheers Patrick

**Comment by lucidrains** [comment]
patience, the paper came out 2 days ago

**Comment by FurkanGozukara** [comment]
> patience, the paper came out 2 days ago

From read me I only see fragments of code

I would like to make a tutorial for this repo on my channel SECourses

I already have a great tts tutorial but yours looking even better 

[**Master Deep Voice Cloning in Minutes: Unleash Your Vocal Superpowers! Free and Locally on Your PC**](https://youtu.be/OiMRlqcgDL0)

[![image](https://github.com/152334H/DL-Art-School/assets/19240467/1a5b1d93-7fc8-473b-b88a-d44beee105a9)
](https://youtu.be/OiMRlqcgDL0)
