### ISSUE TITLE
I believe in case of grouped quantisers we need different optimisation for sampling strategy

### ISSUE THREAD

**Issue by inspirit** [lucidrains/soundstorm-pytorch#39]
Hi Phil,

i think that when we have grouped quantisers optimisation that allow full sampling for first quantiser only will not work because groups works through concatenation and there is no residual sums between groups, the summing happens only inside each group.

Correct me if I'm wrong, but i think we need to fully sample each group's first quantiser for generation to work?

**Comment by lucidrains** [comment]
don't think i will return to working on this paper any time soon, esp given the success of E2TTS

**Comment by inspirit** [comment]
do you think there is no place for RQ anymore? :)

**Comment by lucidrains** [comment]
@inspirit RQ isn't going anywhere, just i see the light with E2TTS. it is over for TTS

**Comment by inspirit** [comment]
ahh, i see i thought you mean e2 type of conditional generation will remove the need for quantisers/decoders, which is unlikely of course considering different data type domains etc.

**Comment by AlexSteveChungAlvarez** [comment]
> @inspirit RQ isn't going anywhere, just i see the light with E2TTS. it is over for TTS

Can you explain why? I was recently reading about SoundStorm, but decided to read the issue before going ahead with the code.
I went to the E2TTS repo you have to read the issue too and in there I found that almost nobody has made it work.

I saw people on that repo mentioned voicebox (maybe as base for E2TTS), but I've heard samples from voicebox and soundstorm and it sounded like soundstorm had better outputs, then why is E2TTS the correct way?

**Comment by lucidrains** [comment]
@AlexSteveChungAlvarez you went there too early, multiple people have made it work by now
